version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=schoolmanager
    volumes:
      - schoolmanager:/var/lib/postgresql/data


  keycloak-db:
    image: postgres:15
    container_name: keycloak-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_FEATURES: scripts,preview
      KC_SCRIPTS_UPLOAD_ENABLED: true

      # Variáveis de exportação removidas
      # KC_EXPORT_REALM: school-manager-realm
      # KC_EXPORT_USERS: "true"
      # KC_IMPORT: /opt/keycloak/data/export/school-manager-realm.json

    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - keycloak-network
    volumes:
      # O volume agora aponta para o diretório de IMPORTAÇÃO
      - ./keycloak-export:/opt/keycloak/data/import
      # Certifique-se de que o arquivo local `school-manager-realm.json` esteja em
      # um subdiretório chamado `keycloak-export`

volumes:
  schoolmanager:
  keycloak-db:
  keycloak-export:

networks:
  keycloak-network:
    name: keycloak-network
